import type { MachineCategory } from '../../types';

export const MACHINES: MachineCategory[] = [
  {
    id: 'vehicles',
    name: 'のりもの',
    emoji: '🚗',
    description: 'いろんな のりものを あつめよう！',
    themeColor: 0x4488ff,
    bgColor: 0x1a0a2e,
    frameColor: 0x6622aa,
    itemIds: ['shinkansen', 'airplane', 'bus', 'policeCar', 'excavator', 'helicopter', 'rocket', 'ship'],
  },
  {
    id: 'sea',
    name: 'うみのいきもの',
    emoji: '🐠',
    description: 'うみの なかまを あつめよう！',
    themeColor: 0x2266bb,
    bgColor: 0x0a1a2e,
    frameColor: 0x225588,
    itemIds: ['whale', 'dolphin', 'clownfish', 'octopus', 'seaTurtle', 'jellyfish', 'manta', 'seahorse'],
  },
  {
    id: 'flags',
    name: 'こっき',
    emoji: '🏁',
    description: 'せかいの こっきを あつめよう！',
    themeColor: 0xcc2233,
    bgColor: 0x2e0a0a,
    frameColor: 0x882222,
    itemIds: ['flagJapan', 'flagUSA', 'flagBrazil', 'flagFrance', 'flagChina', 'flagAustralia', 'flagIndia', 'flagKorea'],
  },
  {
    id: 'instruments',
    name: 'がっき',
    emoji: '🎵',
    description: 'いろんな がっきを あつめよう！',
    themeColor: 0x2299cc,
    bgColor: 0x0a1a2e,
    frameColor: 0x226688,
    itemIds: ['piano', 'guitar', 'taiko', 'trumpet', 'violin', 'harmonica', 'cymbal', 'recorder'],
  },
  {
    id: 'dinosaurs',
    name: 'きょうりゅう',
    emoji: '🦕',
    description: 'きょうりゅうを あつめよう！',
    themeColor: 0xcc8833,
    bgColor: 0x2e1a0a,
    frameColor: 0x886622,
    itemIds: ['trex', 'triceratops', 'stegosaurus', 'pteranodon', 'brachiosaurus', 'velociraptor', 'ankylosaurus', 'parasaurolophus'],
  },
  {
    id: 'insects',
    name: 'むし',
    emoji: '🐛',
    description: 'いろんな むしを あつめよう！',
    themeColor: 0x66aa22,
    bgColor: 0x1a2e0a,
    frameColor: 0x447722,
    itemIds: ['beetleKabuto', 'beetleKuwagata', 'butterfly', 'ladybug', 'dragonfly', 'grasshopper', 'firefly', 'mantis'],
  },
  {
    id: 'animals',
    name: 'どうぶつ',
    emoji: '🐾',
    description: 'かわいい どうぶつを あつめよう！',
    themeColor: 0x22aa66,
    bgColor: 0x0a2e1a,
    frameColor: 0x228844,
    itemIds: ['lion', 'elephant', 'giraffe', 'panda', 'rabbit', 'penguin', 'cat', 'dog'],
  },
  {
    id: 'japan',
    name: 'にほんのぶんか',
    emoji: '🏯',
    description: 'にほんの ぶんかを あつめよう！',
    themeColor: 0xcc4422,
    bgColor: 0x2e0a0a,
    frameColor: 0x883322,
    itemIds: ['castle', 'torii', 'fujisan', 'sakuramochi', 'koinobori', 'daruma', 'chochin', 'manekiNeko'],
  },
];
